#!/bin/bash
# Hospital Management System - Getting Started Guide

echo "================================"
echo "Hospital Management System"
echo "Getting Started"
echo "================================"
echo ""

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 DOCUMENTATION INDEX${NC}"
echo ""
echo "Start with these files in order:"
echo ""
echo "1. ${GREEN}STATUS.txt${NC}"
echo "   Quick overview of what's included"
echo ""
echo "2. ${GREEN}INDEX.md${NC}"
echo "   Complete navigation guide"
echo ""
echo "3. ${GREEN}PRODUCTION_READY.md${NC}"
echo "   Detailed status and next steps"
echo ""
echo "4. ${GREEN}QUICK_REFERENCE.md${NC}"
echo "   Developer commands and API reference"
echo ""
echo "5. ${GREEN}DEPLOYMENT_GUIDE.md${NC}"
echo "   How to deploy to production"
echo ""
echo ""
echo -e "${BLUE}🚀 QUICK START${NC}"
echo ""
echo "Development:"
echo "  1. Run: setup.bat (Windows)"
echo "  2. Access: http://localhost:3000"
echo "  3. Admin: http://localhost:8000/admin"
echo ""
echo "Production:"
echo "  1. Read: DEPLOYMENT_GUIDE.md"
echo "  2. Run: docker-compose up -d"
echo "  3. Access: http://yourdomain.com"
echo ""
echo ""
echo -e "${BLUE}📦 WHAT'S INCLUDED${NC}"
echo ""
echo "✅ Full-stack Application (Django + React)"
echo "✅ Professional UI with responsive design"
echo "✅ Production Docker setup"
echo "✅ Nginx reverse proxy configuration"
echo "✅ Complete documentation (5+ guides)"
echo "✅ Security best practices"
echo "✅ Ready to deploy"
echo ""
echo ""
echo -e "${BLUE}🎯 NEXT STEPS${NC}"
echo ""
echo "Choose your path:"
echo ""
echo "A) I want to develop locally"
echo "   → Run setup.bat and access http://localhost:3000"
echo ""
echo "B) I want to prepare for interview"
echo "   → Read PRODUCTION_READY.md and add sample data"
echo ""
echo "C) I want to deploy to production"
echo "   → Read DEPLOYMENT_GUIDE.md and choose your provider"
echo ""
echo "D) I want to customize it"
echo "   → Read QUICK_REFERENCE.md → Customization section"
echo ""
echo ""
echo -e "${GREEN}✨ Application Status: READY${NC}"
echo ""
echo "Backend: Running on http://localhost:8000"
echo "Frontend: Running on http://localhost:3000"
echo "Database: Configured and ready"
echo "Admin: Available at http://localhost:8000/admin"
echo ""
echo "Read STATUS.txt for quick overview"
echo "Read INDEX.md for complete navigation"
echo ""
